version: '3'

services:
  chat:
    build: .
    environment:
      SERVICE_PORT: 8081
      DATABASE_URL: jdbc:postgresql://postgres:5432/chat_db
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: postgres
    ports:
      - 8081:8081
  postgres:
    image: postgres:13.3
    environment:
      POSTGRES_DB: chat_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres