server:
  port: ${SERVICE_PORT:8081}
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/chat_db}
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:pass_123}
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
  liquibase:
    enabled: true
    change-log: 'classpath:db/changelog/db.changelog-master.yaml'
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/chat_db}
    user: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:pass_123}
logging:
  level:
    org.springframework.transaction: DEBUG
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG
    com.dmitry.muravev.chat.logging: DEBUG
springfox:
  documentation:
    enabled: ${SWAGGER_ENABLED:true}

jwt:
  token:
    secret: ${ACCESS_TOKEN_SECRET:accessSecret}
    expiration-time: ${ACCESS_TOKEN_EXPIRATION_TIME:3600}

registration:
  default-role: ROLE_USER

masking:
  sensitive-headers:
    - authorization
  body-patterns:
    -
      pattern: '"password"\s*:\s*"[a-zA-Z0-9_\-!?\.\,&*$#@]{3,25}"'
      replace: '"password": "***"'
